### ISSUE TITLE
Flag for enforcing positive definiteness or linesearch

### ISSUE THREAD

**Issue by abelsiqueira** [JuliaSmoothOptimizers/Krylov.jl#100]

**Comment by dpo** [comment]
... in CG, as is done in CR.

**Comment by amontoison** [comment]
I don't really understand what you want; a keyword argument `linesearch` set to true by default?

**Comment by dpo** [comment]
This is an old issue but I think we meant to implement the variant of CG that is used in linesearch methods:
* if pAp ≤ 0 at the first iteration, return r
* if pAp ≤ 0 later, return the previous p.

**Comment by amontoison** [comment]
Do you still want it? All solvers in Krylov.jl return the solution of the system, so it's a little bit different if we return r or p.

**Comment by dpo** [comment]
Sorry, we don't return the last p, we return the last x. It's Alg 17.1 in NW's book.

**Comment by amontoison** [comment]
I looked for algorithm 17.1 in Numerial Optimization (edition 1 and 2) of Jorge Nocedal and Stephen Wright and I didn't find it. Did you mean something else with NW?

**Comment by dpo** [comment]
I meant 7.1
