### ISSUE TITLE
Complex linear systems

### ISSUE THREAD

**Issue by amontoison** [JuliaSmoothOptimizers/Krylov.jl#103]
Currently,  we are only able to solve linear systems with Float32 and Float64 types.
It will be relevant to generalized them to Float16, BigFloat (#99) and Complex types.

### Krylov methods

- [x] CG (#490)
- [x] CR (#508)
- [x] SYMMLQ (#506)
- [x] CG-LANCZOS without shifts (#509)
- [x] CG-LANCZOS with shifts (#509)
- [x] MINRES (#504)
- [x] MINRES-QLP (#505)
- [x] DQGMRES (#491)
- [x] DIOM (#489)
- [x] GMRES (#481)
- [x] FOM (#486)
- [x] USYMLQ (#496)
- [x] USYMQR (#495)
- [x] TRICG (#492)
- [x] TRIMR (#494)
- [x] TRILQR (#498)
- [x] CGS (#507)
- [x] BICGSTAB (#481)
- [x] BILQ (#497)
- [x] QMR (#481)
- [x] BILQR (#517)
- [x] CGLS (#500)
- [x] CRLS (#501)
- [x] CGNE (#503)
- [x] CRMR (#502)
- [x] LSLQ (#515)
- [x] LSQR (#514)
- [x] LSMR (#513)
- [x] LNLQ (#510)
- [x] CRAIG (#511)
- [x] CRAIGMR (#512)
- [x] GPMR (#483)

**Comment by amontoison** [comment]
With #134, methods work in any floating-point data type.
Next step, complex linear systems.

**Comment by abelsiqueira** [comment]
Is this done?

**Comment by amontoison** [comment]
No, we need to generalize some functions like `sym_givens` before. It's not difficult but I need to take the time to update all methods one by one.

**Comment by amontoison** [comment]
Some users require the support of complex numbers :
https://discourse.julialang.org/t/linear-problem-with-multiple-shifts/69086/7
