### ISSUE TITLE
Preconditioned CR

### ISSUE THREAD

**Issue by amontoison** [JuliaSmoothOptimizers/Krylov.jl#120]
With #84, preconditioned CR doesn't work anymore even if we are not in a linesearch or trust-region context : `lineseach = false` and `radius = 0`.
#54

**Comment by dpo** [comment]
What does "doesn't work" mean? Could you give an example?

**Comment by amontoison** [comment]
"Doesn't work" means that CR returns `solved = false` at the end of the resolution with a preconditioner.
Sorry it wasn't clear.

Example:
```julia
n = 10
A = ones(n, n) + (n-1) * I
b = n * [1:n;]
M = 1/n * opEye(n)
(x, stats) = cr(A, b, M=M)
println(stats.solved)
```
I thought that CR wasn't able to solve the problem. It's not the case (good news!). 
```julia
r = b - A * x
rNorm = norm(r) / norm(b)
println(rNorm)
1.3e-16
```
I suppose that the problem comes from the estimate of ‖r‖². The expression could be different with a preconditioner.
https://github.com/JuliaSmoothOptimizers/Krylov.jl/blob/3714d55019871fddb95163e1b98fce392574708a/src/cr.jl#L190

It's the condition `tired = iter > itmax` that stop CR in that situation.

**Comment by dpo** [comment]
What residual does CR return? Could you show the final output? It's still not clear to me what the problem is.

**Comment by amontoison** [comment]
```julia
julia> stats.residuals
21-element Array{Float64,1}:
 19.621416870348583
 57.00567003997249 
 55.08441552210965 
 55.08441552210965
  ⋮                
 55.08441552210965 
 55.08441552210965 
```
And the real norm residuals computed with norm(b - A *x) are : 
```julia
46.40620468146287
3.370400129833633e-14
2.4613922385709617e-14
2.4868995751603507e-14
  ⋮  
2.4868995751603507e-14
2.4868995751603507e-14
```

**Comment by amontoison** [comment]
If we use 
```julia
rNorm² = @kdot(n, r, r)
rNorm = sqrt(rNorm²)
```
instead of
```
rNorm² = rNorm² - α * ρ
rNorm = sqrt(rNorm²)
```
we have the solution in only 3 iterations and `stats.solved = true`
```julia
stats.residuals
3-element Array{Float64,1}:
19.621416870348583     
4.640620468146287     
1.4349927862323324e-15
```

**Comment by dpo** [comment]
The update formula for the residual norm was developed for the Euclidean norm. Note that if you supply a preconditioner, the residual is no longer measured in the Euclidean norm, so we should look for an appropriate update.
