### ISSUE TITLE
Add iter on stats

### ISSUE THREAD

**Issue by abelsiqueira** [JuliaSmoothOptimizers/Krylov.jl#13]
Add iter on stats (`cg.jl`, at least).

**Comment by dpo** [comment]
I care less and less about the number of iterations because it's not representative of the computational effort. The most expensive operations in Krylov methods are usually the operator-vector products, so that's what I count. The rest is a O(1) number of vector and scalar operations per iteration.

**Comment by dpo** [comment]
Does this seem reasonable? I think when comparing methods, the most intuitive basis for comparison is the number of operator-vector products (and transposed operator-vector products).

**Comment by abelsiqueira** [comment]
Yes, sorry, I forgot to reply. I was considering it for total number of inner iterations on tron, but op-v products work as well, and I also agree that is a better means of comparing.

**Comment by dpo** [comment]
Ok, thanks.
