### ISSUE TITLE
Preconditioned LSMR

### ISSUE THREAD

**Issue by jlperla** [JuliaSmoothOptimizers/Krylov.jl#147]
I noticed that https://github.com/JuliaSmoothOptimizers/Krylov.jl/blob/master/src/lsmr.jl  has preconditioning, but couldn't figure out how to use the preconditioning to solve a simple LLS problem.  Do you have a MWE that shows how to use preconditioners (e.g. something like modifying)
```
N = 10
σ = 0.1
X = rand(N,3)
c = rand(3)
y = X * c + σ * randn(N)
c_estimate = X \ y
@show cond(X' * X)
Krylov.lsmr(X, y)  # how to add preconditioning
```
Also, and this is more of a theoretical question.... but does preconditioning typically help if the normal equations are ill-conditioned?  Are there typical tricks which work for those setups, etc.

I thought someone suggested that algebraic multigrid helped precondition the sorts of matrices that come about in LLS, but I could be wildly wrong.

**Comment by amontoison** [comment]
If you want to use a preconditioner, you need to wrap it with a `LinearOperator`.
```julia
using LinearOperators
M = PreallocatedLinearOperator(P) # P my preconditioner
lsmr(X, y, M=M)
```

About preconditioning, I suppose that It's still relevant to do a scaling with a diagonal preconditioner
when the normal equation is ill-conditioned.

It's @dpo that implement this  `lsmr`, he should more helpful than me for your questions.

**Comment by jlperla** [comment]
Thanks so much!  I tried this approach, but I can't get even a trivial identify preconditioner to work.  Is this a preconditioner intended for the Normal equations (i.e. should I be looking at `Diagonal(X' * X)` or something else)?

For example, the following doesn't work.
```
using LinearOperators, Krylov, LinearAlgebra, SparseArrays
N = 10
σ = 0.1
X = rand(N,3)
c = rand(3)
y = X * c + σ * randn(N)
c_estimate = X \ y
P = I(length(c))# ???? shape mismatch
M = PreallocatedLinearOperator(P) # P my preconditioner
Krylov.lsmr(X, y, M=M)  # how to add preconditioning
```

@dpo  If you have any advice on this stuff, it would be appreciated.  In economics we sometimes get enormous and ill-conditioned linear least squares problems, and I want to experiment with various preconditioning strategies.

**Comment by dpo** [comment]
The preconditioner M is intended to be a left preconditioner, i.e., it changes the norm in which the residual is measured:
```julia
julia> M = PreallocatedLinearOperator(Matrix(1.0I, N, N))
julia> Krylov.lsmr(X, y, M=M)
([0.640782, 0.522669, 0.252274],
Simple stats
  solved: true
  inconsistent: true
  residuals:  [  2.4e+00  3.2e-01  2.3e-01  2.3e-01 ]
  Aresiduals: [  6.9e+00  1.9e-01  1.1e-02  6.4e-14 ]
  status: found approximate minimum least-squares solution
)
```
If you want to use a right preconditioner, the simplest is to pass in your preconditioned X directly. For instance, it's often recommended to scale the columns of X so they have unit norm:
```julia
function scale_ls!(A)
  s = ones(size(A, 2))
  for j = 1 : size(A, 2)
    i = A.colptr[j]
    k = A.colptr[j+1] - 1
    nj = i <= k ? norm(A.nzval[i:k]) : 0.0
    if nj > 0.0
      A.nzval[i:k] ./= nj
      s[j] = nj
    end
  end
  return s  # s contains the diagonal elements of the (right) diagonal scaling
end

# or the dense version
# s = [1 / norm(X[:,k]) for k = 1 : size(X,2)]
# X *= diagm(0 => s)

julia> X = sparse(X);
julia> s = scale_ls!(X);
julia> c_lsmr, stats = lsmr(X, y)
([1.00927, 1.16582, 0.424589],
Simple stats
  solved: true
  inconsistent: true
  residuals:  [  2.4e+00  3.5e-01  2.3e-01  2.3e-01 ]
  Aresiduals: [  3.7e+00  1.4e-01  5.2e-03  1.1e-13 ]
  status: found approximate minimum least-squares solution
)
julia> c_lsmr ./ s   # same as solution found previously
3-element Array{Float64,1}:
 0.6407818243114393
 0.5226686593350174
 0.252273982089151
```

Other popular preconditioners are the incomplete LU and QR factorizations of X, although they doesn't perform consistently. For LU, it's important to use a factorization that keep L well conditioned (e.g., with rook pivoting). You'll find other strategies in https://dl.acm.org/citation.cfm?id=3014057.

Here are a few other pointers:
* http://stanford.edu/group/SOL/talks/17cseLUprecon.pdf
* https://epubs.siam.org/doi/abs/10.1137/140975358
* https://cerfacs.fr/wp-content/uploads/2016/03/tuma.pdf

Feel free to get in touch if we can help.

**Comment by abelsiqueira** [comment]
You can also add a regularization term, e.g.:
```julia
lsmr(X, y, λ=1e-1)
```
In this case, `lsmr` solvers `(X' * X + λ^2 I) c = X' * y`.

**Comment by abelsiqueira** [comment]
Closing. Please reopen or create a new issue if there's any need for further discussion.
