### ISSUE TITLE
cg returns NaN for singular problem

### ISSUE THREAD

**Issue by abelsiqueira** [JuliaSmoothOptimizers/Krylov.jl#189]
```julia
Q = [1.0 0.0; 0.0 0.0]
g = -Q * ones(2) + [0.0; 1.0]
x, ks = Krylov.cg(Q, -g)
```
Output:
```
([NaN, NaN], 
Simple stats
  solved: false
  inconsistent: false
  residuals:  [ 1.4e+00  1.4e+00      NaN      NaN      NaN ]
  Aresiduals: []
  status: maximum number of iterations exceeded
)
```

**Comment by dpo** [comment]
CG would only be well defined if g is in the range of Q here. But the system is inconsistent. So it's expected that CG would crash:
```
julia> Q \ g
2-element Array{Float64,1}:
  -1.0
 Inf
```

**Comment by amontoison** [comment]
The best solver for that kind of system is `minres_qlp`. I think it's the most powerful Krylov solver for symmetric matrix.
It finds the solution of minimum-norm that minimise ||b - Ax||.

```julia
x, ks = Krylov.minres_qlp(A, g)
([-1.0000000000000002, -1.0087576610494615e-16], 
Simple stats
  solved: false
  inconsistent: true
  residuals:  [ 1.4e+00  1.0e+00  9.4e-01 ]
  Aresiduals: [ 7.1e-01  1.3e-16 ]
  status: solution good enough given atol and rtol
)
```

**Comment by abelsiqueira** [comment]
I thought the division by zero could be detected and returned as a failure, with `inconsistent = true`.
Thanks for the suggestion, Alexis.

**Comment by dpo** [comment]
It's true that we should be more careful when computing alpha. If pAp == 0 and there's no trust region constraint, we should probably guess that the system is inconsistent.

**Comment by amontoison** [comment]
I open a pull request for that.
