### ISSUE TITLE
Add documentation about preconditioners

### ISSUE THREAD

**Issue by amontoison** [JuliaSmoothOptimizers/Krylov.jl#222]
It will be useful to show how to build relevant preconditioners for our Krylov methods in the documentation with the help of linear operators.
- Jacobi
- SPAI
- Incomplete L |D| Lᵀ
- ILU
- LLᵀ
- LDLᵀ

**Comment by dpo** [comment]
Sounds good. But LLᵀ and LDLᵀ would cause termination in a single iteration, no?

**Comment by amontoison** [comment]
LLᵀ and LDLᵀ could be used to solve systems with `M` and `N` within saddle-point and SQD systems. Is it still relevant to call it preconditioners when a process is done in elliptic norms?

**Comment by dpo** [comment]
M and N are in a different category than preconditioners.
