### ISSUE TITLE
Sign of the regularization in minres

### ISSUE THREAD

**Issue by tmigot** [JuliaSmoothOptimizers/Krylov.jl#255]
I suspect there is a bug with the sign of the regularization in `minres`. Following the doc, it should solve the shifted linear system

    (A + λ I) x = b

Taking A = I, b = 1, and λ=0.5 should return a vector with 2/3. However, it returns 2, which would correspond to put -λ.

```
using Krylov, LinearAlgebra
In = diagm(0 => ones(3))
b = ones(3)
(x, stats) = minres(In, b, λ = 0.5) # return ≈2*ones(3)
(x, stats) = minres(In, b, λ = -0.5) # return ≈2/3*ones(3)
```

**Comment by dpo** [comment]
Thank you for catching this!
