### ISSUE TITLE
Preallocate workspace for solvers

### ISSUE THREAD

**Issue by dpo** [JuliaSmoothOptimizers/Krylov.jl#264]
### Krylov methods

- [x] CG
- [x] CR
- [x] SYMMLQ
- [x] CG-LANCZOS
- [x] CG-LANCZOS-SHIFT-SEQ
- [x] MINRES
- [x] MINRES-QLP
- [x] DQGMRES
- [x] DIOM
- [x] USYMLQ
- [x] USYMQR
- [x] TRICG
- [x] TRIMR
- [x] TRILQR
- [x] CGS
- [x] BICGSTAB
- [x] BILQ
- [x] QMR
- [x] BILQR
- [x] CGLS
- [x] CRLS
- [x] CGNE
- [x] CRMR
- [x] LSLQ
- [x] LSQR
- [x] LSMR
- [x] LNLQ
- [x] CRAIG
- [x] CRAIGMR

For MINRES, this could take the form (not tested)
```julia
function minres(A, b :: AbstractVector{T}; kwargs...) where T <: AbstractFloat
  x = similar(b)
  r1 = similar(b)
  window = kwargs.get(:window, 5)
  err_vec = Vector{T}(undef, window)
  minres!(A, b, x, r1, err_vec; kwargs...)
end

function minres!(A, b, x, r1, err_vec;
                M=opEye(), λ :: T=zero(T), atol :: T=√eps(T)/100,
                rtol :: T=√eps(T)/100, etol :: T=√eps(T),
                window :: Int=5, itmax :: Int=0, conlim :: T=1/√eps(T),
                verbose :: Int=0) where T <: AbstractFloat
  ...
  x .= 0
  r1 .= b
  err_vec .= 0
  ...
end
```
The objective is for `minres!()` to not allocate at all. We could also define
```julia
abstract type KrylovSolver end
mutable struct MinresSolver <: KrylovSolver
  x
  r1
  err_vec
  # maybe default parameter values...
  function MinresSolver(A, b)
    new(...)
  end
end
```
and pass an instance of `MinresSolver` around.

@amontoison @geoffroyleconte

**Comment by amontoison** [comment]
Speak of the devil ! We were talking about it this afternoon with Geoffroy.

**Comment by dpo** [comment]
😈

**Comment by amontoison** [comment]
I have something in mind, I will open a pull request when it's ready. It should not break GPU support, which a little bit tricky.

**Comment by amontoison** [comment]
@geoffroyleconte 
I let you try to add this feature for MINRES.
To not break GPU support you should parameterized your `solver` like that :
```
abstract type KrylovSolver{S} end
mutable struct MinresSolver{S} <: KrylovSolver{S}
  x  :: S
  r1 :: S
  ...
end
```
where `S` is `Vector{Float64}`, `CuVector{Float64}`, ... It should not be `Float32`, `Float64`, ... 
You can find the variable names of ` MinresSolver` here : https://github.com/JuliaSmoothOptimizers/Krylov.jl/blob/master/test/test_alloc.jl#L41
 
Like Dominique proposed you can create a function like that after :
```
function minres(A, b :: AbstractVector{T}; kwargs...) where T <: AbstractFloat
  solver = ... # create your MinresSolver 
  minres!(A, b, solver; kwargs...)
end
```

In `minres!`, you can add the following lines at the beginning to reuse all the actual code of `minres` :
```
x = solver.x
r1 = solver.r1
....
```
You only to update the initialization of the variables and add a check to verify that `eltype(S) == T`.
