### ISSUE TITLE
Constructors KrylovSolver

### ISSUE THREAD

**Issue by tmigot** [JuliaSmoothOptimizers/Krylov.jl#299]
Thanks for the amazing work including the KrylovSolver.

I just find having `MinresSolver(A, b)` as a constructor not practical since only the size of A and the type of b is needed.
For instance, in an optimization solver, we typically want to initialize the KrylovSolver at the initialization step where the size and the type is known but we don't have access yet to the matrix and the rhs.

Maybe we could have a `MinresSolver(m, n, S)` by default and an additional one with `MinresSolver(A, b)`. What do you think?

**Comment by amontoison** [comment]
`Solver(A, b)` was used to do the link between in-place and not in-place methods (https://github.com/JuliaSmoothOptimizers/Krylov.jl/blob/master/src/bilq.jl#L32-L35) when I added the KrylovSolvers.
Your constructor `Solver(m, n, S)` is an excellent idea. I added it with #300.
