### ISSUE TITLE
UndefRefError when using BigFloat and non-matricial linear operators with the LinearOperators revamp

### ISSUE THREAD

**Issue by abelsiqueira** [JuliaSmoothOptimizers/Krylov.jl#329]
I have `ERROR: UndefRefError: access to undefined reference` when using the LinearOperators revamp with my revamp of `lbfgs` on BigFloat, but I can recreate with a simple version.
This happens because the `prod!` function tries to use a `Vector{BigFloat}(undef, nvar)`.

```julia
using Krylov, LinearOperators

function my_prod!(res, v, α, β)
  res .= α * v + β * res
  res
end

op = LinearOperator(BigFloat, 3, 3, true, true, my_prod!)
v = ones(BigFloat, 3)

cg(op, v)
```
The error happens inside `cg.jl` with operation `mul!(Ap, A, p)`. (Line 99).

I could have checked for `β == 0`, but since we're creating memory inside `CgSolver`, we could initialize it to 0. It doesn't fail to Float64, because it `Vector{Float64}(undef, n)` returns values of the order `1e-310`.

**Comment by amontoison** [comment]
The issue is with your function `my_prod!` Abel :
```
using Krylov, LinearOperators

v = ones(BigFloat, 3)

function my_prod!(res, v, α, β)
  res .= α * v + β * res
  res
end

op = LinearOperator(BigFloat, 3, 3, true, true, my_prod!)
x = rand(BigFloat,  3)
y = Vector{BigFloat}(undef, 3)
A = rand(BigFloat, 3, 3)

α = rand(BigFloat)
β = rand(BigFloat)
mul!(y, op, x) # fails
mul!(y, A, x) # works

function my_prod2!(res, v, α, β)
  if β == 0
    @. res = α * v
  else
    @. res = α * v + β * res
  end
  return res
end

op2 = LinearOperator(BigFloat, 3, 3, true, true, my_prod2!)
x = rand(BigFloat,  3)
y = Vector{BigFloat}(undef, 3)
mul!(y, op2, x) # works
cg(op2, v) # works
```

**Comment by abelsiqueira** [comment]
Sure, I mentioned that in my post. But if the cost of initializing to 0 is the same as initializing to `undef`, shouldn't we initialize to 0? It would be safer.

**Comment by abelsiqueira** [comment]
By the way, let me know if the cost is not the same.

**Comment by amontoison** [comment]
> Sure, I mentioned that in my post. But if the cost of initializing to 0 is the same as initializing to `undef`, shouldn't we initialize to 0? It would be safer.

Do you know a constructor that initialize to 0 ?
I only know `S(undef, n)`.

**Comment by amontoison** [comment]
I can use my functions https://github.com/JuliaSmoothOptimizers/Krylov.jl/blob/master/src/krylov_utils.jl#L185-L197 but It will be slower.

**Comment by abelsiqueira** [comment]
You're right, I forgot about that. Thanks. I'll close this and focus on LinearOperators' side.
