### ISSUE TITLE
How would one supply an initial guess?

### ISSUE THREAD

**Issue by PetrKryslUCSD** [JuliaSmoothOptimizers/Krylov.jl#341]
symmlq, minres: Would it be possible to supply an initial guess of the solution? So that the method could be use to improve that guess instead of computing the solution from scratch?

**Comment by dpo** [comment]
The recommended way to do that is shift your system. If you have initial guess x for Ax=b, compute r = b - Ax, solve A * ∆x = r, and then update x <- x + ∆x.

We could have an interface to do that automatically.

**Comment by PetrKryslUCSD** [comment]
That is true. OK, let's not complicate the UI.

**Comment by amontoison** [comment]
@PetrKryslUCSD, we added in-place Krylov methods recently and it's possible to supply an initial guess of the solution now.
It will be available with the next release for information.

```
solver = MinresSolver(A, b)
solver.x .= x0
minres!(solver, A, b, restart=true)
```

**Comment by PetrKryslUCSD** [comment]
But you were right. It is not a big deal to have the user handle this.
