### ISSUE TITLE
Add KrylovStats in KrylovSolver

### ISSUE THREAD

**Issue by tmigot** [JuliaSmoothOptimizers/Krylov.jl#361]
To continue pre-allocating things, it could be interesting to also have the `KrylovStats` in the `KrylovSolver`.

### Krylov methods

- [x] CG
- [x] CR
- [x] SYMMLQ
- [x] CG-LANCZOS
- [x] CG-LANCZOS with shifts
- [x] MINRES
- [x] MINRES-QLP
- [x] DQGMRES
- [x] DIOM
- [x] USYMLQ
- [x] USYMQR
- [x] TRICG
- [x] TRIMR
- [x] TRILQR
- [x] CGS
- [x] BICGSTAB
- [x] BILQ
- [x] QMR
- [x] BILQR
- [x] CGLS
- [x] CRLS
- [x] CGNE
- [x] CRMR
- [x] LSLQ
- [x] LSQR
- [x] LSMR
- [x] LNLQ
- [x] CRAIG
- [x] CRAIGMR

**Comment by amontoison** [comment]
Thank you for the help Tangi!

**Comment by tmigot** [comment]
Great job, thanks!
