### ISSUE TITLE
LSMR Documentation Errors

### ISSUE THREAD

**Issue by RoyiAvital** [JuliaSmoothOptimizers/Krylov.jl#380]
I found some issues in the documentation of the [LSMR Function](https://juliasmoothoptimizers.github.io/Krylov.jl/dev/solvers/ls/#Krylov.lsmr):

1. Using LSQR instead of LSMR:  
![image](https://user-images.githubusercontent.com/7347975/128697548-987b07ca-c1c0-4357-ab7a-e9769f74835c.png)

2. I think you should define $ {|left\| x \right\|}_{E} $. Because some define it as $ \sqrt{ {x}^{T} E x } $ and some as $ \sqrt{ {x}^{T} {E}^{-1} x } $.
3. There is undefined `y` in:  
![image](https://user-images.githubusercontent.com/7347975/128697668-915f6b76-4a37-4466-b6c4-9c9bed66c9fa.png)

**Comment by RoyiAvital** [comment]
Looks good! Now, the problem is if I have $ \left\| D x \right\|}_{2}^{2} $ which is equivalent to $ \left\| x \right\|}_{ {D}^{T} D }^{2} $ according to documentation I need to pass $ N = {\left( {D}^{T} D \right)}^{-1} $ which is an issue in case $ D $ is sparse (Since the inverse won't be).

Could it be that documentation is wrong about this?

**Comment by amontoison** [comment]
I didn't use the same notation on Slack. It's a little bit confusing...
The documentation is right, you need to pass a matrix or an operator that model the inverse of `(DᵀD)⁻¹`.
In pratice, we never compute the inverse of `(DᵀD)⁻¹`.
- If D is square and nonsingular, you can compute a `LU` factorization of D and do an operator that performs the foward and backward sweeps.
- If D is rectangular, you can compute the `LLᵀ` factorization of `DᵀD` or the `QR` of `D` such that `RᵀR = DᵀD`.

**Comment by amontoison** [comment]
```
using LinearOperators

n, m = size(D)
lu_D = lu(D)
opN = LinearOperator(Float64, n, m, true, true, (y, v, α, β) -> (ldiv!(y, lu_D', v) ; ldiv!(lu_D, y)))

F = D' * D
n, m = size(F)
llt_F = cholesky(F)
opN = LinearOperator(Float64, n, m, true, true, (y, v, α, β) -> ldiv!(y, llt_F, v))
```

You can verify that `opN * v` and `(D' * D) \ v` return the same result.
