### ISSUE TITLE
Confusing error with no provenance

### ISSUE THREAD

**Issue by PetrKryslUCSD** [JuliaSmoothOptimizers/Krylov.jl#443]
I got this really weird error about iteration: 
```
ERROR: LoadError: MethodError: no method matching iterate(::Krylov.MinresSolver{Float64, Vector{Float64}})                                                            
Closest candidates are:                                                            
  iterate(::Union{LinRange, StepRangeLen}) at range.jl:821                         
  iterate(::Union{LinRange, StepRangeLen}, ::Integer) at range.jl:821              
  iterate(::T) where T<:Union{Base.KeySet{<:Any, <:Dict}, Base.ValueIterator{<:Dict}} at dict.jl:695                                                                  
  ...                                                                              
Stacktrace:                                                                        
 [1] indexed_iterate(I::Krylov.MinresSolver{Float64, Vector{Float64}}, i::Int64)   
   @ Base .\tuple.jl:92                                                            
 [2] two_stage_free_enh(cdir::String, sim::String, make_model::typeof(make_model)) 
   @ FinEtoolsRapidHarmonicVA C:\Users\pkonl\Documents\00WIP\FinEtoolsRapidHarmonicVA.jl\src\ModelUtilities.jl:398  
...
```
Unfortunately doesn't say where from your sources this comes, and I'm not able to locate the offending line.

The solver is called as:
```
            @show met, alg, itmax
            (DU, stats) = met(alg, (-omega^2*M + K), r0; atol = 0.0, rtol = 0.0, itmax = itmax, history=true)
```
where
```
(met, alg, itmax) = (Krylov.minres!, ┌────────────────────┬──────────────────────────┬──────────────────┐                                                             
│ Krylov.MinresSolver│        Precision: Float64│ Architecture: CPU│               
├────────────────────┼──────────────────────────┼──────────────────┤               
│           Attribute│                      Type│              Size│               
├────────────────────┼──────────────────────────┼──────────────────┤               
│                  Δx│           Vector{Float64}│                 0│               
│                   x│           Vector{Float64}│             19440│               
│                  r1│           Vector{Float64}│             19440│               
│                  r2│           Vector{Float64}│             19440│               
│                  w1│           Vector{Float64}│             19440│               
│                  w2│           Vector{Float64}│             19440│               
│                   y│           Vector{Float64}│             19440│               
│                   v│           Vector{Float64}│                 0│               
│             err_vec│           Vector{Float64}│                 5│               
└────────────────────┴──────────────────────────┴──────────────────┘               
Simple stats                                                                       
 solved: false                                                                     
 inconsistent: false                                                               
 residuals: []                                                                     
 Aresiduals: []                                                                    
 status: unknown                                                                   
, 5)          
```
I hope you have some ideas. Many thanks!

**Comment by PetrKryslUCSD** [comment]
julia> using Pkg; Pkg.status();                                                    
     Project FinEtoolsRapidHarmonicVA v1.0.0                                       
      Status `C:\Users\pkonl\Documents\00WIP\FinEtoolsRapidHarmonicVA.jl\Project.toml`                                                                                
  [7d9fca2a] Arpack v0.5.3                                                         
  [6e4b80f9] BenchmarkTools v0.7.0                                                 
  [3a989f29] CoNCMOR v0.1.0 `https://github.com/PetrKryslUCSD/CoNCMOR.jl.git#master`                                                                                  
  [91bb5406] FinEtools v5.2.6                                                      
  [e9187c00] FinEtoolsDeforLinear v1.2.1                                           
  [f67ccb44] HDF5 v0.15.7                                                          
  [42fd0dbc] IterativeSolvers v0.9.2                                               
  [682c06a0] JSON v0.21.2                                                          
  [ba0b0d4f] Krylov v0.7.7                                                         
  [0b1a1467] KrylovKit v0.5.3                                                      
  [2679e427] Metis v1.0.0                                                          
  [8314cec4] PGFPlotsX v1.4.1                                                      
  [295af30f] Revise v3.1.20                                                        
  [286e6d88] SymRCM v0.2.1                                                         
  [8bb1440f] DelimitedFiles                                                        
  [37e2e46d] LinearAlgebra                                                         
  [2f01184e] SparseArrays                                                          
  [10745b16] Statistics  

julia> versioninfo()                                                               
Julia Version 1.7.0-rc1                                                            
Commit 9eade6195e (2021-09-12 06:45 UTC)                                           
Platform Info:                                                                     
  OS: Windows (x86_64-w64-mingw32)                                                 
  CPU: AMD Ryzen 7 4700U with Radeon Graphics                                      
  WORD_SIZE: 64                                                                    
  LIBM: libopenlibm                                                                
  LLVM: libLLVM-12.0.1 (ORCJIT, znver2)                                            
Environment:                                                                       
  JULIA_PKG_SERVER =                                                               
  JULIA_SSL_CA_ROOTS_PATH =

**Comment by amontoison** [comment]
Hi @PetrKryslUCSD !
In-place methods only return an updated solver workspace (one output) and you have an error because you specify two outputs.

The following code should work:
```
 @show met, alg, itmax
met(alg, (-omega^2*M + K), r0; atol = 0.0, rtol = 0.0, itmax = itmax, history=true)  # It returns alg
DU, stats = alg.x, alg.stats  # you can also use `solution(alg)` and `statistics(alg)`
```

Other example : 
```
(x, stats) = minres_qlp(A, b, rtol=0.0, atol=0.0, history=true)  # Not in-place
println(norm(b - A * x))

solver = MinresQlpSolver(A, b)
minres_qlp!(solver, A, b, rtol=0.0, atol=0.0, history=true)  # In-place
println(norm(b - A * solver.x))

**Comment by amontoison** [comment]
We introduce the in-place methods with the release 0.7.4 (26 July 2021) but we only finalize the API and the documentation with the release 0.7.7 (8 September 2021).
We changed the output of the in-place methods between these two releases but it will not change anymore now !
