### ISSUE TITLE
`M == LinearAlgebra.I` too slow

### ISSUE THREAD

**Issue by vpuri3** [JuliaSmoothOptimizers/Krylov.jl#462]
```julia
julia> using LinearAlgebra

julia> A = Matrix(1.0I, 1000, 1000);

julia> Q = qr(A).Q;

julia> @time Q == I; # ultra slow
 ```

https://github.com/JuliaSmoothOptimizers/Krylov.jl/blob/329d5dd6a872a2c47b754ba8ba0a1bbdd6ae87a1/src/cg.jl#L59

replace with something like IterativeSolvers.Identity:
https://github.com/JuliaLinearAlgebra/IterativeSolvers.jl/blob/master/src/common.jl#L28-L32

**Comment by ChrisRackauckas** [comment]
Or `=== I` is fine, because then you'd be checking `isa UniformScaling` which is type level and doesn't require checking every single value.

**Comment by amontoison** [comment]
I prefer the second solution with `=== I`.
The PR #463 should solve your problem.

**Comment by vpuri3** [comment]
fantastic, thank you @amontoison  👯‍♂️
