### ISSUE TITLE
Preconditioners

### ISSUE THREAD

**Issue by dpo** [JuliaSmoothOptimizers/Krylov.jl#52]
We should add preconditioners in the obvious places (e.g., `cg()`).

# Preconditioners roadmap

- [x] CG
- [x] CG_LANCZOS
- [ ] CG_LANCZOS_SHIFT_SEQ
- [x] CR
- [x] MINRES
- [x] SYMMLQ
- [x] CGLS
- [x] CGNE
- [x] CRAIG
- [x] CRAIGMR
- [x] CRMR
- [x] LSLQ
- [x] LSMR
- [x] LSQR
- [x] CRLS

**Comment by Xx-fractale-xX** [comment]
# Preconditioners roadmap

- [ ] CG
- [ ] CG_LANCZOS
- [ ] CG_LANCZOS_SHIFT_SEQ
- [ ] CR
- [x] MINRES
- [x] SYMMLQ
- [x] CGLS
- [ ] CGNE
- [ ] CRAIG
- [ ] CRAIGMR
- [ ] CRMR
- [x] LSLQ
- [x] LSMR
- [x] LSQR
- [x] CRLS

**Comment by Xx-fractale-xX** [comment]
As issue #45, we should use preallocation for preconditioners. I don't know if we can update `variants.jl` this time, `M` is a keyword argument.
Maybe we could move `preallocated_LinearOperator` and `preallocated_symmetric_LinearOperator` functions in `LinearOperators`?

**Comment by dpo** [comment]
Yes, we should certainly have preallocated operators in LinearOperators.

**Comment by Xx-fractale-xX** [comment]
Almost finished! `CRAIG` and `CRAIGMR` are the last ones.
