### ISSUE TITLE
convert function for solvers

### ISSUE THREAD

**Issue by geoffroyleconte** [JuliaSmoothOptimizers/Krylov.jl#585]
It could be practical to have something like:

```julia
convert(::Type{KrylovSolver{T, FC}}, solver::MinresSolver) where {T, FC} = MinresSolver(...)
```

to convert a `solver` from `Float32` to `Float64` for example. However I'm not sure what should be the way to implement this. Should the user provide `FC` or could it be inferred from `T` ?

**Comment by amontoison** [comment]
The user should provide `S` (`Vector{ComplexF32}`, `CuVector{Float64}`), ...)
`T` and `FC` are determined from `S`.

Is it not easier to just build a new solver with the constructor `XyzSolver(n, m, S)` ? 
I can add `n` and `m` attributes in the solver such that
```julia
convert(::Type{MinresSolver{T, FC, S}}, solver::MinresSolver) where {T, FC, S} = MinresSolver(solver.n, solver.m, S)
```

**Comment by geoffroyleconte** [comment]
Yes, but that was in case we would want to keep the current solution for using warm start later for example.
