### ISSUE TITLE
fill out residual in output stats

### ISSUE THREAD

**Issue by vpuri3** [JuliaSmoothOptimizers/Krylov.jl#612]
```julia
julia> Krylov.gmres(rand(4,4), rand(4))
([1.592026952483488, 0.6156821203288784, -1.0350317175731996, 0.6436006056238142], Simple stats
 niter: 4
 solved: true
 inconsistent: false
 residuals: []
 Aresiduals: []
 κ₂(A): []
 status: solution good enough given atol and rtol
)
```

**Comment by vpuri3** [comment]
ahh, thank you. I will make that change in LinearSolve

**Comment by amontoison** [comment]
@vpuri3 I also added an option `ldiv` in all methods to support both `mul!` and `ldiv!` functions for the preconditioners.

**Comment by vpuri3** [comment]
thanks, @amontoison. I will make that a part of https://github.com/SciML/LinearSolve.jl/pull/171 when I get to it in ~3 weeks.  :D
