### ISSUE TITLE
Suggestion: Overhauled minres implementation?

### ISSUE THREAD

**Issue by amartinhuertas** [JuliaSmoothOptimizers/Krylov.jl#652]
Dear `Krylov.jl` developers,

thanks for developing this fantastic package.

I was wondering if you have ever considered implementing an improved version of `minres.jl` along the lines followed here:

https://web.stanford.edu/group/SOL/software/minres/

in particular, under the header `30 Apr 2020: Matlab minres overhauled (see minres20.zip below).`, the point starting with `The main stopping rule requires the residual ...`

This applies whenever one is using a preconditioner `M`, and essentially amounts to also consider (in an efficient way) the residual of the unpreconditioned system `Ax=b` to determine when to stop convergence, instead of (solely) the residual of the preconditioned system.

Thanks!
@amartinhuertas

**Comment by amontoison** [comment]
Hi @amartinhuertas!

We are unable to compute cheaply `||b - Ax_k||` if a preconditioner is provided, which means that we must do an additional matrix-vector product at each iteration for `A * x_k`. The efficient way to do it is just to reuse the same storage to store the residual `r_k = b - A * x_k`.

we recently added [callbacks](https://juliasmoothoptimizers.github.io/Krylov.jl/dev/callbacks/) to add custom stopping conditions.
If you set absolute and relative tolerances in MINRES, you should be able to only rely on this stopping conditions.
The callback example is exactly what you need.

**Comment by dpo** [comment]
I agree. The callback is the right tool here as you have to compute ‖Ax - b‖ explicitly anyways.

**Comment by amartinhuertas** [comment]
@amontoison @dpo Thanks for your answers! 

Sure, I can compute the 2-norm of the residual of the true system at each iteration, as you suggest. 

But note that the strategy pursued in that link is a bit different. Let me copy and paste Matlab code here:

```Matlab
      if precon>0 & istop>0 & istop<=5
         % Preconditioned system thinks it satisfied rtol.
         % See if Ax = b is satisfied to rtol0.
         if x0norm==0
            xnorm  = dxnorm;
            rnormk = norm(b - minresxxxA( A,x ) - shift*x);
         else
            xt     = x0 + x;
            xnorm  = norm(xt);
            rnormk = norm(b - minresxxxA( A,xt ) - shift*xt);
         end
         epsr   = (Anorm*xnorm + bnorm)*rtol0;
         if rnormk <= epsr
            istop = 1;
            fprintf('\n rnormk small enough: %8.1e    epsr =%8.1e', rnormk, epsr)
         elseif numrtol<5 & rtol>eps   % Reduce rtol
            numrtol = numrtol + 1;
            rtol    = rtol/10;
            fprintf('\n%7g %2i: rtol reduced to%8.1e', itn,numrtol, rtol)
            fprintf('    rnormk =%8.1e    epsr =%8.1e', rnormk, epsr)
            istop = 0;
         else
            istop = 10;
         end
      end
```

Basically, when the solver claims convergence using the (cheap) preconditioned residual, it double-checks the true residual of the system. If the true residual of the system is not "small enough", then it makes rtol 10 times and continues iterating with the preconditioned residual. It keeps going until the true residual is "small enough" or it has reduced rtol 10^5 times. D

Do you understand the point? It only calculates the true residual of the system at most 5 times.

**Comment by dpo** [comment]
@amartinhuertas I'm very familiar with the strategy you are quoting. You can do the same with callbacks, which is what we're suggesting, and is more flexible than modifying MINRES itself.

**Comment by amartinhuertas** [comment]
> @amartinhuertas I'm very familiar with the strategy you are quoting. You can do the same with callbacks, which is what we're suggesting, and is more flexible than modifying MINRES itself.

Ok, great. Good call! Thanks!

**Comment by amontoison** [comment]
@amartinhuertas 
You can use the following callbacks with all methods in `Krylov.jl`:
```julia
mutable struct Callback{T}
  A::AbstractMatrix{T}
  b::Vector{T}
  r::Vector{T}
  tol::T
end

function (callback::Callback)(solver::KrylovSolver)
  # check the cheap preconditioned residual
  converged = solver.stats.residuals[end] <= callback.tol
  if converged
    # double-checks the true residual of the system
    mul!(callback.r, callback.A, callback.x)
    callback.r .-= callback.b
    converged = norm(callback.r) ≤ callback.tol
    if !converged
      callback.tol = callback.tol / 10
    end
  end
  return converged
end

amartinhuertas_callback = Callback(A, b, r, tol)
(x, stats) = minres_qlp(A, b, history=true, atol=0.0, rtol=0.0, ctol=0.0, callback=amartinhuertas_callback)
```

**Comment by amartinhuertas** [comment]
> @amartinhuertas You can use the following callbacks with all methods in Krylov.jl:

Thanks @amontoison ! The solution I am currently using after @dpo and your initial comments works along the same lines.
