### ISSUE TITLE
Add stopping criterion on time limit

### ISSUE THREAD

**Issue by tmigot** [JuliaSmoothOptimizers/Krylov.jl#661]
We could check at the end of each iteration wether or not we respect a `max_time::Float64`

**Comment by amontoison** [comment]
Il will work soon on the stopping conditions. Il will add this feature.

**Comment by amontoison** [comment]
Hi @tmigot, do you have an optimization solver in JSOSolvers.jl with a stopping creteria based on time limit?
I would like to use the same name for the keyword argument.

**Comment by tmigot** [comment]
I think almost all the optimization solvers have it now, see, for instance, https://github.com/JuliaSmoothOptimizers/JSOSolvers.jl/blob/21b97086a4b55b6893b7c5a2482e400aded16d68/src/R2.jl#L109

**Comment by amontoison** [comment]
I opened #730 such that we can validate together. I will update all other solvers after.
