### ISSUE TITLE
[documentation] Change the category of USYMLQ and USYMQR

### ISSUE THREAD

**Issue by amontoison** [JuliaSmoothOptimizers/Krylov.jl#665]
Currently `USYMLQ` and `USYMQR` are in the category `Non-Hermitian indefinite linear systems` but we could move `USYMLQ` into the category `Least-norm problems` and `USYMQR` into `Least-squares problems`.

**Comment by dpo** [comment]
Yes, that would make more sense. It should also be explained somewhere that both could be used to solve square linear systems (consistent in the case of USYMLQ).
