### ISSUE TITLE
First Release

### ISSUE THREAD

**Issue by abelsiqueira** [JuliaSmoothOptimizers/Krylov.jl#68]
Krylov doesn't have a release yet (on METADATA), we should make one supporting 0.6 and 0.7.
What needs to be included?
- [x] #62 
- [x] #63 
- [x] #67

**Comment by dpo** [comment]
Yes. I'll try to validate those this week.

**Comment by abelsiqueira** [comment]
Those three are done, so maybe we should do the first release to get that out of the way? That would be release 0.2, I think. Zenodo is up and attobot is configured, I think.
What it strictly necessary for a release?
- [ ] Check `REQUIRE`;
