### ISSUE TITLE
Unnecessary `eltype` restriciton on A

### ISSUE THREAD

**Issue by vpuri3** [JuliaSmoothOptimizers/Krylov.jl#736]
it should not matter if `eltype(A) == eltype(b)`. What should matter is that the multiplication (with `*` or `mul!`) produce an object of the same `eltype` as `b`.

I understand the reason for this restriction is to avoid unseen allocations due to type conversions.
https://github.com/JuliaSmoothOptimizers/Krylov.jl/blob/cec1dd814292a012080b63c30665e89f839a04bc/src/fgmres.jl#L126
However, the assertion makes sense as a constraint on subtypes of `AbstractMatrix` where multiplication of say a `ComplexF64` matrix with a `Float64` vector will not be a Float64 vector.
```julia
julia> ones(ComplexF64, 4, 4) * ones(Float64, 4) |> eltype
ComplexF64 (alias for Complex{Float64})
```
However, the constraint isn't symmetric: multiplying a real matrix with a complex vector results in a complex vector without any allocations.
```julia
julia> ones(Float64, 4, 4) * ones(ComplexF64, 4) |> eltype
ComplexF64 (alias for Complex{Float64})

julia> using LinearAlgebra

julia> A = ones(Float64, 4, 4); b=ones(ComplexF64, 4); x=copy(b);

julia> @allocated mul!(x, A, b)
0
```

I encountered this issue today while writing a PDE operator using the FFT. My `A` matrix-free (written using `SciMLOperators`) and accepts/returns `Vector{Float64}` types. However, as `A` uses the FFT internally, its `eltype` must be `ComplexF64`.

I therefore argue that this constraint is unnecessarily restrictive, especially for matrix-free operators, and should be replaced with a `warning """eltype(A) \neq eltype(b). This could lead to unseen allocations in operator application. """` and a `Tricks.static_hasmethod(LinearAlgebra.mul!, typeof((x, A, b)))`. Additionally you could include a conditional to promote types for `AbstractMatrices`

```julia
if isa(A, AbstractMatrix) & (eltype(A) \neq eltype(b))
    Ta = eltype(A)
    Tb = eltype(b)
    T = promote_type(Ta, Tb)
    Ta !== T && A = T.(A)
    Tb !== T && b = T.(b)
end
```

Please let me know what you think. Happy to follow this up with a PR. :D

**Comment by amontoison** [comment]
Hi @vpuri3!
The issue is that I use the type of the right-hand side `b` to determine the type of the workspace (`KrylovSolver`).
If the result on the in-place operator-vector products is not of type `FC`, we will have an error.

**Comment by amontoison** [comment]
@vpuri3 I'm not sure to understand your operator based on FFT. `eltype(A) = ComplexF64`, `eltype(b) = Float64` and the result is always `Float64`?

**Comment by vpuri3** [comment]
> @vpuri3 I'm not sure to understand your operator based on FFT. `eltype(A) = ComplexF64`, `eltype(b) = Float64` and the result is always `Float64`?

I understand that. As in the second example in the issue description, you can have a complex vector/ workspace with a real matrix. the only constraint should be that the result of matrix vector product should be of the same type of the vector itself.

**Comment by amontoison** [comment]
OK, I understand the issue now. Can we do something like this to handle this special case?
```julia
eltype(A) == FC || Tricks.static_hasmethod(LinearAlgebra.mul!, typeof((x, A, b))) || error("eltype(A) ≠ $FC") 
```

**Comment by vpuri3** [comment]
Yes that works! I'd also recommend adding a warning as in the issue description.
```julia
if eltype(A) !== FC
  @warn "..."
  if !Tricks.static_hasmethod(LinearAlgebra.mul!, typeof((x, A, b)))
    throw(MethodError(mul!, (x, A, b)))
  end
end
```

**Comment by amontoison** [comment]
Is it not an issue for you to always have a warning when you call a krylov method with your linear operator?

It's not an issue to relax the constraint on the type of `A`. 🙂

**Comment by amontoison** [comment]
@vpuri3 
I propose this modification, is it good for you?
```julia
eltype(A) == FC || error("eltype(A) ≠ $FC")
```
by
```julia
eltype(A) == FC || @warn "eltype(A) ≠ eltype(b). This could lead to errors or additional allocations in operator-vector products."
```
I can use a `sed` command to update all methods.
