### ISSUE TITLE
`ktypeof(::AbstractVector)` is breaking between 0.9.0 and 0.9.1

### ISSUE THREAD

**Issue by charleskawczynski** [JuliaSmoothOptimizers/Krylov.jl#749]
Hello, thank you for the great package!

It appears that [`ktypeof`](https://juliasmoothoptimizers.github.io/Krylov.jl/stable/api/#Krylov.ktypeof) is a part of the API, however, https://github.com/JuliaSmoothOptimizers/Krylov.jl/pull/705 changed the behavior of `ktypeof` for `AbstractVector` and has broken our CI based on a patch update.

I'm wondering whether it's expected that users overload `ktypeof` for their own types, or if this was a mistake to be reverted (so that we know how to move forward).

**Comment by amontoison** [comment]
Hi @charleskawczynski!
Can you give an example of your `AbstractVector`?
I can update the function `ktypeof` to keep the old behavior for your array type:
https://github.com/JuliaSmoothOptimizers/Krylov.jl/blob/main/src/krylov_utils.jl#L212

**Comment by charleskawczynski** [comment]
So, I think we were relying on [this form](https://github.com/JuliaSmoothOptimizers/Krylov.jl/blob/main/src/krylov_utils.jl#L215), however, or "FieldVector" types are similar to BlockArrays:

```julia
struct FieldVector{T, M} <: BlockArrays.AbstractBlockVector{T}
    values::M
end
```

so, it looks like the return type of `Krylov.ktypeof` has changed.

I think we can recover the previous return type easily by defining our own `Krylov.ktypeof`, and make it work a bit more generally (e.g., for Cu-backed arrays). But I'm now wondering if we should instead define `OurArrayType(undef)` and `OurArrayType(undef, ::Int)` instead?

**Comment by amontoison** [comment]
I opened #750 to keep the old behaviour of `ktypeof` for your type `FillVector`. What the name of your package?

**Comment by charleskawczynski** [comment]
The package is https://github.com/CliMA/ClimaCore.jl, but the fix will not apply to CuArrays, which we need. I have a solution on our side:

```julia
import ClimaComms

# https://github.com/JuliaSmoothOptimizers/Krylov.jl/issues/749
function Krylov.ktypeof(v::S) where {S <: Fields.FieldVector}
    return ClimaComms.array_type(v){eltype(parent(v))}
end

ClimaComms.array_type(x::Fields.FieldVector) = _array_type(x)

@inline _array_type(x::Fields.FieldVector) = _array_type(x, propertynames(x))
@inline _array_type(x::Fields.FieldVector, pns::Tuple{}) = Any

@inline _array_type(x::Fields.Field) = ClimaComms.array_type(x)
@inline _array_type(x::Fields.FieldVector, sym::Symbol) =
    _array_type(getproperty(x, sym))

@inline _array_type(x::Fields.FieldVector, pns::Tuple{Symbol}) =
    _array_type(getproperty(x, first(pns)))

@inline _array_type(x::Fields.FieldVector, pns::Tuple) = promote_type(
    _array_type(getproperty(x, first(pns))),
    _array_type(x, Base.tail(pns))...,
)
```
But I think this is pretty specific to our code

**Comment by amontoison** [comment]
No problem @charleskawczynski 
If you need a modification for your package here, don't hesitate to open a new issue. :slightly_smiling_face:
