### ISSUE TITLE
Problem with Matrix-vector operation in CRMR

### ISSUE THREAD

**Issue by Xx-fractale-xX** [JuliaSmoothOptimizers/Krylov.jl#80]
I tried to understand why the test with a preconditioner didn't passed with `Julia 0.7`. And the problem seems to come from the new version of `LinearOperators`. 

With `Julia 0.6` :
```julia
CRMR: system of 2 equations in 10 variables
Aprod     ‖A'r‖       ‖r‖
    1  5.48e-02  3.01e-03
    3  1.35e-02  8.68e-03
    5  2.30e-16  3.70e-17
CRMR: residual: 2.6e-15
‖x - xmin‖ = 8.8e-17
```

With `Julia 0.7`
```julia
CRMR: system of 2 equations in 10 variables
Aprod     ‖A'r‖       ‖r‖
    1  5.48e-02  3.01e-03
    3  4.25e-02  6.58e-03
    5  1.14e-01  1.84e-02
    7  1.20e+00  1.94e-01
    9  1.36e+02  2.20e+01
   11  1.75e+06  2.84e+05
   13  2.91e+14  4.71e+13
   15  8.04e+30  1.30e+30
   17  6.12e+63  9.91e+62
   19  3.55e+129  5.75e+128
   21       Inf  1.93e+260
   23       NaN       NaN
   25       NaN       NaN
CRMR: residual:     NaN
```
The Aᵗp operation returns a wrong value (without preconditioner).
I also tested with a `CRMR` version that allow matrix instead of LinearOperator with julia 0.7. And this time we have the good result.
```julia
crmr2(A, b, M=M, verbose=true)
CRMR: system of 2 equations in 10 variables
Aprod     ‖A'r‖       ‖r‖
    1  5.48e-02  3.01e-03
    3  1.35e-02  8.68e-03
    5  2.30e-16  3.70e-17
```

**Comment by dpo** [comment]
It's difficult to know what you're showing in such a long output. Is there anything else than the last test to look at? Many CRMR tests are random, so the outputs would be different. But of course, Inf and NaN can only be errors. Could you isolate one case that exhibits the erroneous behavior?

**Comment by Xx-fractale-xX** [comment]
I updated my comment, I forgot that tests were random with `CRMR`.
In `test_crmr.jl` we have:
```julia
A = 0.5 * [19.0 17.0 15.0 13.0 11.0 9.0 7.0 5.0 3.0 1.0;
            2.0  2.0  2.0  2.0  2.0 2.0 2.0 2.0 2.0 2.0]
b = [1.0; 0.0]
M = LinearOperator(Diagonal(1 ./ (A * A')))
```
And I remarked that `M = Diagonal(1 ./ (A * A'))` is a
```julia
2×2 Diagonal{Float64,Array{Float64,1}}
```
with `julia 0.7`, whereas with `julia 0.6` it's a : 
```julia 
2×2 Diagonal{Float64}
```
Maybe the problem can come from that too.
I will try to isolate one case that exhibits the erroneous behavior.
