### ISSUE TITLE
use of AbstractArray

### ISSUE THREAD

**Issue by rveltz** [JuliaSmoothOptimizers/Krylov.jl#935]
Hi,

In the matrix free context, I would like to apply an operator to a Matrix representing the solution of a PDE. In order to use Krylov.jl, I have to pass AbstractVectors hence reshape / views. Is there a better workflow?

Thank you a lot

**Comment by amontoison** [comment]
Hi Romain!
Is this solurion not good enough for you:
https://jso.dev/Krylov.jl/dev/matrix_free/#Example-with-discretized-PDE ?

I have another alternative if you want but I would like to know the type of the matrix before (just `Matrix` or something on GPU / custom type)?

**Comment by amontoison** [comment]
You allocate `32 bits` at each `vec` / `reshape`.
So it's quite cheap but you could remove these allocations with a custom workspace: https://jso.dev/Krylov.jl/dev/custom_workspaces/

You just need to create your own `AbstractVector` that wraps your matrix
The drawback is that you will lose by default the dispatch to BLAS / CUBLAS / rocBLAS for the linear algebra operations.

I only recommend it for an advanced use like multi-GPU with MPI.

**Comment by rveltz** [comment]
Ok it just halfed my computation time and I did not optimise it. 

With bifurcationKit, I regret now not having tried earlier, the fact that you can reuse the krylov space is a massive boost in perfs, I thought KrylovKit was good enough

**Comment by amontoison** [comment]
If you use it on a GPU, the speed-up will be even greater because allocations and deallocations are more expensive, and the garbage collection system works differently.
KrylovKit.jl is generic but was not developed for performances and also doesn't support preconditioners which is quite relevant for Krylov methods.

**Comment by rveltz** [comment]
The only con is the lack of general eigensolver like in KrylovKit

**Comment by amontoison** [comment]
Yes, you're totally right. I should implement one eigensolver one day.

Off-topic: Romain, I will probably visit JB-Caillau at INRIA the second week of January.

**Comment by rveltz** [comment]
Great! Please ping me the week before so I can free some time.

**Comment by rveltz** [comment]
By the way, thanks for your detailed answers, I am typing on my phone so I am not really verbose
