### ISSUE TITLE
Allocations tests

### ISSUE THREAD

**Issue by amontoison** [JuliaSmoothOptimizers/Krylov.jl#97]
We should check the allocations of each solver (old and future ones). It's a good way to find mistakes and verify that implementations perform well.
# Allocations tests roadmap
## Methods already in Krylov.jl
- [x] CG_LANCZOS
- [x] CG_LANCZOS_SHIFT_SEQ
- [x] CG
- [x] CR
- [x] CGLS
- [x] CRLS
- [x] CGNE
- [x] CRAIG
- [x] CRMR
- [x] CRAIGMR
- [x] LSLQ
- [x] LSMR
- [x] LSQR
- [x] MINRES
- [x] SYMMLQ
- [x] DQGMRES
- [x] DIOM
- [x] CGS
## Future methods
- [x] USYMLQ
- [x] USYMQR
- [x] TFQMR
- [x] GMRES
- [x] FOM

**Comment by amontoison** [comment]
Whew, `SYMMLQ` is the last one. Maybe we could do a new release after #123 ?

**Comment by dpo** [comment]
https://github.com/JuliaLang/METADATA.jl/pull/21990 Many thanks @amontoison for all your contributions lately! (There are still a number of open pull requests... yikes!)
